import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import ContextProvider from './context/context'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'Pdf Modifier',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Toaster toastOptions={{
            className: 'font-semibold',
          }} />
          <Navbar />
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
